<?php

namespace blackcube\admin\components;

class RbacConstants
{
    public const PERMISSION_CATEGORY_CREATE = 'CATEGORY:CREATE';
    public const PERMISSION_CATEGORY_DELETE = 'CATEGORY:DELETE';
    public const PERMISSION_CATEGORY_UPDATE = 'CATEGORY:UPDATE';
    public const ROLE_CATEGORY_MANAGER = 'CATEGORY:MANAGER';

    public const PERMISSION_TAG_CREATE = 'TAG:CREATE';
    public const PERMISSION_TAG_DELETE = 'TAG:DELETE';
    public const PERMISSION_TAG_UPDATE = 'TAG:UPDATE';
    public const ROLE_TAG_MANAGER = 'TAG:MANAGER';

    public const PERMISSION_NODE_CREATE = 'NODE:CREATE';
    public const PERMISSION_NODE_DELETE = 'NODE:DELETE';
    public const PERMISSION_NODE_UPDATE = 'NODE:UPDATE';
    public const ROLE_NODE_MANAGER = 'NODE:MANAGER';

    public const PERMISSION_COMPOSITE_CREATE = 'COMPOSITE:CREATE';
    public const PERMISSION_COMPOSITE_DELETE = 'COMPOSITE:DELETE';
    public const PERMISSION_COMPOSITE_UPDATE = 'COMPOSITE:UPDATE';
    public const ROLE_COMPOSITE_MANAGER = 'COMPOSITE:MANAGER';

    public const PERMISSION_USER_CREATE = 'USER:CREATE';
    public const PERMISSION_USER_DELETE = 'USER:DELETE';
    public const PERMISSION_USER_UPDATE = 'USER:UPDATE';
    public const ROLE_USER_MANAGER = 'USER:MANAGER';

    public const PERMISSION_PREVIEW = 'PREVIEW';

    public const ROLE_ADMIN = 'ADMIN';

}
