<?php
/**
 * ImportForm.php
 *
 * PHP version 8.2+
 *
 * @author Philippe Gaultier <pgaultier@gmail.com>
 * @copyright 2010-2025 Philippe Gaultier
 * @license https://www.blackcube.io/license
 * @link https://www.blackcube.io
 */

namespace blackcube\admin\models;

use blackcube\admin\Module;
use blackcube\core\behaviors\FileSaveBehavior;
use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

/**
 * ImportForm Model
 *
 * @author Philippe Gaultier <pgaultier@gmail.com>
 * @copyright 2010-2025 Philippe Gaultier
 * @license https://www.blackcube.io/license
 * @link https://www.blackcube.io
 */
class ImportForm extends Model
{

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        // $behaviors['savefiles'] = [
        //     'class' => FileSaveBehavior::class,
        //     'filesAttributes' => ['importFile'],
        // ];
        return $behaviors;
    }


    /**
     * @var UploadedFile
     */
    public $importFile;

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return [
            [['importFile'], 'filter', 'filter' => function($value) {
                if ($value === null) {
                    return $value;
                } else {
                    return empty(trim($value)) ? null : trim($value);
                }
            }],
            [['importFile'], 'required'],
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLabels()
    {
        return [
            'importFile' => Module::t('models', 'Import file'),
        ];
    }
}
