<?php
/**
 * ImportForm.php
 *
 * PHP version 8.0+
 *
 * @author Philippe Gaultier <pgaultier@redcat.io>
 * @copyright 2010-2022 Redcat
 * @license https://www.redcat.io/license license
 * @version XXX
 * @link https://www.redcat.io
 * @package blackcube\admin\models
 */

namespace blackcube\admin\models;

use blackcube\admin\Module;
use blackcube\core\behaviors\FileSaveBehavior;
use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

/**
 * ImportForm Model
 *
 * @author Philippe Gaultier <pgaultier@redcat.io>
 * @copyright 2010-2022 Redcat
 * @license https://www.redcat.io/license license
 * @version XXX
 * @link https://www.redcat.io
 * @package blackcube\admin\models
 */
class ImportForm extends Model
{

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        // $behaviors['savefiles'] = [
        //     'class' => FileSaveBehavior::class,
        //     'filesAttributes' => ['importFile'],
        // ];
        return $behaviors;
    }


    /**
     * @var UploadedFile
     */
    public $importFile;

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return [
            [['importFile'], 'filter', 'filter' => function($value) {
                if ($value === null) {
                    return $value;
                } else {
                    return empty(trim($value)) ? null : trim($value);
                }
            }],
            [['importFile'], 'required'],
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLabels()
    {
        return [
            'importFile' => Module::t('models', 'Import file'),
        ];
    }
}
